### ISSUE TITLE
Rate limiting not working

### ISSUE THREAD

**Issue by justinbkay** [malomohq/shopify-graphql-elixir#22]
Hi,

I'm trying to use your library to access Shopify to download products.  I've tried setting up the rate limiting, but it isn't working for some reason.  I'm not sure if I've missed something or what the deal is.

I've added the gen_state dependency to my mix.exs file:
`{:gen_stage, "~> 1.0"},`

I've started Shopify.GraphQL.Limiter in my supervision tree:

     def start(_type, _args) do
     # List all child processes to be supervised
     children = [
       # Start the Ecto repository
       AppapiPhx.Repo,
       # Start the PubSub system
       {Phoenix.PubSub, name: AppapiPhx.PubSub},
       # Start the endpoint when the application starts
       AppapiPhxWeb.Endpoint,
       # Starts a worker by calling: AppapiPhx.Worker.start_link(arg)
       # {AppapiPhx.Worker, arg},
       Shopify.GraphQL.Limiter
     ]
    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: AppapiPhx.Supervisor]
    Supervisor.start_link(children, opts)
    end

I've added the limiter: true option to my send:

    Shopify.GraphQL.send(%{access_token: token, shop: shop, limiter: true})

I get:

    GenServer.call(:"Elixir.Shopify.GraphQL.Limiter.Producer:image-and-get-it.myshopify.com", {:process, 
    {%Shopify.GraphQL.Operation{query: "query ($numProducts: Int!, $cursor: String){\n  products(first: $numProducts, after: 
    $cursor) {\n    pageInfo {\n      hasNextPage\n    }\n    edges {\n      cursor\n      node {\n        id\n        title\n        
    productType\n        vendor\n        variants(first: 20) {\n          pageInfo {\n            hasNextPage\n          }\n          edges {\n            
    node {\n              id\n              weight\n              title\n              weightUnit\n              sku\n            }\n          }\n        }\n      }\n    }\n  
    }\n}\n", variables: %{cursor: "eyJsYXN0X2lkIjo1MTYwMDAzNzY0MzYxLCJsYXN0X3ZhbHVlIjoiNTE2MDAwMzc2NDM2MSJ9", 
    numProducts: 30}}, %Shopify.GraphQL.Config{access_token: "token", endpoint: 
    "graphql.json", headers: [], host: "myshopify.com", http_client: Shopify.GraphQL.Client.Hackney, http_client_opts: [], 
    json_codec: Jason, limiter: true, limiter_opts: [], path: "admin/api", port: nil, protocol: "https", retry: false, retry_opts: [], 
    shop: "shop", version: nil}}}, :infinity)

Any insight would be greatly appreciated!

**Comment by anthonator** [comment]
The limiter does work. We use it in production. However, I believe there is a race condition that may be shutting the limiter partition down prematurely which results in this error. I’ll look into it.

Thanks for reporting.

**Comment by justinbkay** [comment]
If I set the limiter to false I get this:

    ** (exit) exited in: GenServer.call(false, {:start_child, {{Shopify.GraphQL.Limiter.Partition, :start_link, [[parent: false, 
    partition_id: "rhino-camera-gear.myshopify.com"]]}, :temporary, :infinity, :supervisor, [Shopify.GraphQL.Limiter.Partition]}}, 
    :infinity)
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly 
    because its application isn't started
        (elixir 1.10.4) lib/gen_server.ex:1013: GenServer.call/3
        (shopify_graphql 1.4.0) lib/shopify/graphql/limiter.ex:48: Shopify.GraphQL.Limiter.start_partition/3
        (shopify_graphql 1.4.0) lib/shopify/graphql/limiter.ex:23: Shopify.GraphQL.Limiter.send/3
        (appapi_phx 0.1.9) lib/appapi_phx/shopify/product_load.ex:200: AppapiPhx.Shopify.ProductLoad.do_product_query/5
        (appapi_phx 0.1.9) lib/appapi_phx/shopify/product_load.ex:21: anonymous fn/1 in 
    AppapiPhx.Shopify.ProductLoad.find_active_stores/0
        (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2

**Comment by anthonator** [comment]
I pushed a fix for a limiter of `false` not working.

**Comment by anthonator** [comment]
Just a heads up. I added a limiter option to disable partition monitoring. This should prevent limiter partitions from shutting down which I _think_ should prevent this error from happening. I believe this is a race condition which makes it difficult to verify. If you continue to have problems let me know.

To disable partition monitoring you can pass `monitor: false` to the `:limiter_opts` config option. It's documented in the README.

I'm currently in the process of rebuilding the limiter to hopefully remove this problem.

**Comment by justinbkay** [comment]
Thanks for the update. I'm currently working around this issue by using a sleep function, it might not be the most efficient, but it seems to work reliably.  I'll try to test out the limiter again in the near future.
