### ISSUE TITLE
Close to final version of 2.0?

### ISSUE THREAD

**Issue by axelson** [malomohq/shopify-graphql-elixir#39]
Hi there! :wave: 
Thanks for creating this library! It looks to be very helpful as a means to interface with Shopify.

I'm in the early stage of trying to figure out the approach for a new Shopify app and it would be great to depend on version 2.0 instead of version 1.x but I wanted to try to get a sense of how far off 2.0 is (given that it's already on rc versions).

**Comment by anthonator** [comment]
We have been using the rc version for a while in production. So it should be good to go! The reason it remains in rc is some work I'm doing on the limiter in clustered environments. Even for that use case it works pretty well. I wouldn't hesitate to use the rc at this point.

**Comment by axelson** [comment]
Okay, thanks that's good to know!
